
version: "3"

services:

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  telegram_bot:
    container_name: telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ./entrypoints/bot.sh
    env_file:
      - ./.docker-compose.prod.env
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: